/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#6ffbbe',
        'surface-container-high': '#dce9ff',
        'inverse-on-surface': '#eaf1ff',
        'surface-variant': '#d3e4fe',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#213145',
        'surface-tint': '#4355b9',
        'secondary-container': '#6cf8bb',
        'surface-dim': '#cbdbf5',
        'primary-fixed-dim': '#bac3ff',
        'inverse-primary': '#bac3ff',
        'on-primary-fixed-variant': '#293ca0',
        'tertiary-fixed-dim': '#ffb95f',
        'on-tertiary-container': '#ffc988',
        'primary-fixed': '#dee0ff',
        background: '#f8f9ff',
        'on-secondary-fixed': '#002113',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#d3e4fe',
        'outline-variant': '#c5c5d4',
        secondary: '#006c49',
        'on-secondary-container': '#00714d',
        'surface-container-low': '#eff4ff',
        'on-tertiary-fixed-variant': '#653e00',
        'on-surface-variant': '#454652',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-background': '#0b1c30',
        outline: '#757684',
        primary: '#24389c',
        'on-primary-fixed': '#00105c',
        'tertiary-fixed': '#ffddb8',
        'on-primary-container': '#cacfff',
        tertiary: '#603b00',
        'on-primary': '#ffffff',
        surface: '#f8f9ff',
        'secondary-fixed-dim': '#4edea3',
        'on-surface': '#0b1c30',
        'surface-bright': '#f8f9ff',
        'tertiary-container': '#805000',
        'on-error-container': '#93000a',
        'surface-container': '#e5eeff',
        'on-secondary-fixed-variant': '#005236',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#2a1700',
        'error-container': '#ffdad6',
        'primary-container': '#3f51b5',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '16px',
        xl: '32px',
        xs: '4px',
        base: '4px',
        md: '16px',
        'sidebar-width': '260px',
        sm: '8px',
        'container-max': '1440px',
        lg: '24px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'headline-lg': ['Inter'],
        'label-sm': ['Inter'],
        'headline-sm': ['Inter'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
